<?php 
//MODELO VISTA CONTROLADOR
//MODELO: LÓGICA DE NEGOCIO, CLASES Y MÉTODOS QUE SE COMUNICAN CON LA BBDD
//VISTA: GRÁFICA USUARIO
//CONTROLADOR: INTERMEDIARIO ENTRE MODELO Y VISTA. CREAR OBJETOS, LLAMAR MÉTODOS, ...


?>